name: PR Check
on: [pull_request]

jobs:
  test-components:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0 # fetch all history for codecov

      - uses: actions/setup-node@v3
        with:
          node-version: 20

      - name: Install dependencies
        run: yarn install --immutable

      - name: Test Components
        run: yarn test

  lint-ts:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Install dependencies
        run: yarn install --immutable

      - name: Lint TS
        run: yarn lint-ts
